# File automatically-generated by STM32CubeMX - Do not modify
cmake_minimum_required(VERSION 3.22)
# STM32CubeMX generated symbols (macros)
set(MX_Defines_Syms 
	CORE_CM7 
	USE_HAL_DRIVER 
	STM32H747xx 
	USE_PWR_DIRECT_SMPS_SUPPLY
    $<$<CONFIG:Debug>:DEBUG>
)
# STM32CubeMX generated include paths
set(MX_Include_Dirs
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/inc/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/bus_protocols/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/resource_imp/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/mqtt/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_WPS/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_MBEDTLS/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/netxduo-network-interface-integration/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/cy_log/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/JSON_parser/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/linked_list/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/cy_string/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/network/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-port/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-port/source/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/include/mbedtls/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/whd-bsp-integration/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/whd-bsp-integration/COMPONENT_NETXDUO/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/platform/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/libraries/standard/coreMQTT/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/libraries/standard/coreMQTT/source/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/libraries/standard/coreMQTT/source/interface/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/libraries/standard/backoffAlgorithm/source/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/mqtt/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_MBEDTLS
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_WPS/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_WPS
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_WPS/Utilities/TLV
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-port/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-port/source/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/whd-bsp-integration
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/platform/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/libraries/standard/coreMQTT/source/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/libraries/standard/coreMQTT/source/interface
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/libraries/standard/backoffAlgorithm/source/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_55500/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/firmware/COMPONENT_55500/COMPONENT_SM/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/nvram/COMPONENT_55500/COMPONENT_SONA-IF513/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/clm/COMPONENT_55500/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/core-lib/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/hal/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/common/Inc/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/targets/TARGET_STM32/Inc/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/abstraction-rtos/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/abstraction-rtos/source/COMPONENT_THREADX/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/abstraction-rtos/include/COMPONENT_THREADX/
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_55500
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/inc
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/resource_imp
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/firmware/COMPONENT_55500/COMPONENT_SM
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/clm/COMPONENT_55500
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/hal/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/common/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/targets/TARGET_STM32/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/core-lib/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/abstraction-rtos/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS/Device/ST/STM32H7xx/Include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS/Include
)
# STM32CubeMX generated application sources
set(MX_Application_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/main.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/stm32h7xx_it.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/stm32h7xx_hal_msp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/sysmem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/syscalls.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Startup/startup_stm32h747xx_CM7.s
)

# STM32 HAL/LL Drivers
set(STM32_Drivers_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/../Common/Src/system_stm32h7xx_dualcore_boot_cm4_cm7.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c
)

# Drivers Midllewares

set(Connectivity_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/abstraction-rtos/source/COMPONENT_THREADX/cyabs_rtos_threadx.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/abstraction-rtos/source/cy_worker_thread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/common/Src/cyhal_system.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/common/Src/wifi_bt_if.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/targets/TARGET_STM32/Src/stm32_cyhal_gpio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/targets/TARGET_STM32/Src/stm32_cyhal_lptimer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/targets/TARGET_STM32/Src/stm32_cyhal_sdio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/targets/TARGET_STM32/Src/stm32_cyhal_spi.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/targets/TARGET_STM32/Src/stm32_cyhal_trng.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/targets/TARGET_STM32/Src/stm32_cyhal_uart.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/pal/targets/TARGET_STM32/Src/stm32_cyhal_syspm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/firmware/COMPONENT_55500/COMPONENT_SM/55500A1_bin.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/firmware/COMPONENT_55500/COMPONENT_SM/55500A1-mfgtest_bin.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/clm/COMPONENT_55500/55500A1_clm_blob.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/clm/COMPONENT_55500/55500A1-mfgtest_clm_blob.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/libraries/standard/coreMQTT/source/core_mqtt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/libraries/standard/coreMQTT/source/core_mqtt_state.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-embedded-C/libraries/standard/coreMQTT/source/core_mqtt_serializer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/whd-bsp-integration/cybsp_wifi.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/whd-bsp-integration/COMPONENT_NETXDUO/cy_network_buffer_netxduo.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/aes.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/aesni.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/arc4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/aria.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/asn1parse.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/asn1write.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/base64.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/bignum.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/blowfish.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/camellia.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ccm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/certs.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/chacha20.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/chachapoly.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/cipher.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/cipher_wrap.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/cmac.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ctr_drbg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/debug.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/des.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/dhm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ecdh.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ecdsa.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ecjpake.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ecp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ecp_curves.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/entropy.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/entropy_poll.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/error.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/gcm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/havege.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/hkdf.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/hmac_drbg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/md.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/md2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/md4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/md5.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/memory_buffer_alloc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/net_sockets.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/nist_kw.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/oid.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/padlock.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/pem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/pk.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/pkcs11.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/pkcs12.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/pkcs5.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/pkparse.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/pkwrite.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/pk_wrap.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/platform.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/platform_util.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/poly1305.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/psa_crypto.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/psa_crypto_driver_wrappers.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/psa_crypto_se.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/psa_crypto_slot_management.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/psa_crypto_storage.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/psa_its_file.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ripemd160.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/rsa.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/rsa_internal.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/sha1.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/sha256.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/sha512.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ssl_cache.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ssl_ciphersuites.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ssl_cli.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ssl_cookie.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ssl_msg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ssl_srv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ssl_ticket.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ssl_tls.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/ssl_tls13_keys.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/threading.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/timing.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/version.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/version_features.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/x509.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/x509write_crt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/x509write_csr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/x509_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/x509_crl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/x509_crt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/x509_csr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/ARM/mbedtls/library/xtea.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/cy_log/cy_log.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/JSON_parser/cy_json_parser.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/linked_list/cy_linked_list.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/cy_string/cy_string_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/network/cy_nw_helper_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/connectivity-utilities/network/COMPONENT_NETXDUO/cy_nw_helper.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-port/source/cy_aws_clock.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-port/source/cy_aws_retry_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/aws-iot-device-sdk-port/source/COMPONENT_SECURE_SOCKETS/cy_aws_tcpip_port_secure_sockets.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/netxduo-network-interface-integration/source/cy_netxduo.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/cy_wcm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_MBEDTLS/cy_wps_aes_ctr_ccm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_MBEDTLS/cy_wps_crypto.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_WPS/cy_wcm_wps.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_WPS/cy_wps.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_WPS/cy_wps_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_WPS/cy_wps_enrollee.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_WPS/nn.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-connection-manager/source/COMPONENT_WPS/Utilities/TLV/tlv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/bus_protocols/whd_bus.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/bus_protocols/whd_bus_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/bus_protocols/whd_bus_sdio_protocol.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/bus_protocols/whd_bus_spi_protocol.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_ap.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_buffer_api.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_cdc_bdc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_chip.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_chip_constants.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_clm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_debug.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_events.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_logging.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_management.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_network_if.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_proto.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_resource_if.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_sdpcm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_thread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_wifi.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_wifi_api.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_wifi_p2p.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_commonring.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_flowring.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/src/whd_ring.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/wifi-host-driver/COMPONENT_WIFI6/resources/resource_imp/whd_resources.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/Infineon_Wireless_Connectivity/mqtt/source/cy_mqtt_api.c
)
# Link directories setup
set(MX_LINK_DIRS

)
# Project libraries
set (MX_LINK_LIBS 
    STM32_Drivers
    ${TOOLCHAIN_LINK_LIBRARIES}
    Connectivity	
)
# Interface library for includes and symbols
add_library(stm32cubemx INTERFACE)
target_include_directories(stm32cubemx INTERFACE ${MX_Include_Dirs})
target_compile_definitions(stm32cubemx INTERFACE ${MX_Defines_Syms})

# Create STM32_Drivers static library
add_library(STM32_Drivers OBJECT)
target_sources(STM32_Drivers PRIVATE ${STM32_Drivers_Src})
target_link_libraries(STM32_Drivers PUBLIC stm32cubemx)

# Create Connectivity static library
add_library(Connectivity OBJECT)
target_sources(Connectivity PRIVATE ${Connectivity_Src})
target_link_libraries(Connectivity PUBLIC stm32cubemx)


# Add STM32CubeMX generated application sources to the project
target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${MX_Application_Src})

# Link directories setup
target_link_directories(${CMAKE_PROJECT_NAME} PRIVATE ${MX_LINK_DIRS})

# Add libraries to the project
target_link_libraries(${CMAKE_PROJECT_NAME} ${MX_LINK_LIBS})

# Add the map file to the list of files to be removed with 'clean' target
set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES ADDITIONAL_CLEAN_FILES ${CMAKE_PROJECT_NAME}.map)

# Validate that STM32CubeMX code is compatible with C standard
if((CMAKE_C_STANDARD EQUAL 90) OR (CMAKE_C_STANDARD EQUAL 99))
    message(ERROR "Generated code requires C11 or higher")
endif()